- name: Configure Vagrant box
  hosts: all
  become: true

  tasks:
    - name: Ubuntu | Default packages install
      ansible.builtin.apt:
        update_cache: yes
        pkg:
         - ansible
         - build-essential
         - docker.io
         - g++
         - gcc
         - git
         - htop
         - libffi-dev
         - make
         - net-tools
         - nmap
         - podman
         - python3-dev
         - python3-pip
         - python3-venv
         - ruby
         - ruby-dev
         - vim
         - whois

    - name: Python venv
      command: python3 -m venv /tmp/venv
      args:
        creates: /tmp/venv

    - name: Packer install
      include_role:
        name: diodonfrost.packer

    - name: Vagrant install
      include_role:
        name: diodonfrost.vagrant

    - name: Terraform install
      include_role:
        name: diodonfrost.terraform

    - name: Terragrunt install
      include_role:
        name: diodonfrost.terragrunt

    - name: Sonar-scanner install
      include_role:
        name: diodonfrost.sonar_scanner

    - name: Git-lfs install
      include_role:
        name: diodonfrost.git_lfs

    - name: Ohmyzsh install
      include_role:
        name: diodonfrost.ohmyzsh
      vars:
        ohmyzsh_theme: powerlevel10k/powerlevel10k

    - name: P10k install
      include_role:
        name: diodonfrost.p10k
      vars:
        zsh_plugin: ohmyzsh
