- name: Configure Vagrant box
  hosts: all
  become: true

  tasks:
    - name: Archlinux | Default packages install
      ansible.builtin.pacman:
        update_cache: yes
        pkg:
         - ansible
         - base-devel
         - bzip2
         - docker
         - gcc
         - git
         - htop
         - libffi
         - make
         - net-tools
         - nmap
         - podman
         - python-pip
         - ruby
         - tar
         - unzip
         - vim
         - whois
        state: latest

    - name: Packer install
      include_role:
        name: diodonfrost.packer

    - name: Terraform install
      include_role:
        name: diodonfrost.terraform
    
    - name: Waypoint install
      include_role:
        name: diodonfrost.waypoint

    - name: Terragrunt install
      include_role:
        name: diodonfrost.terragrunt

    - name: Sonar-scanner install
      include_role:
        name: diodonfrost.sonar_scanner

    - name: Git-lfs install
      include_role:
        name: diodonfrost.git_lfs

    - name: Ohmyzsh install
      include_role:
        name: diodonfrost.ohmyzsh
      vars:
        ohmyzsh_theme: powerlevel10k/powerlevel10k

    - name: P10k install
      include_role:
        name: diodonfrost.p10k
      vars:
        zsh_plugin: ohmyzsh

    - name: Archlinux | Update system packages
      community.general.pacman:
        update_cache: true
        upgrade: true
